### ISSUE TITLE
Add Client/Server connectivity

### ISSUE THREAD

**Issue by HeavenlyRain** [EECE3093C/team-project-lua#27]
# Goal of this issue

The goal of this issue is to establish seamless connectivity between the fastAPI server and the React client in our application. This will enable effective communication and data exchange between the server and client components.

# Resources

To accomplish this task, refer to the following resources:
1. fastAPI documentation: https://fastapi.tiangolo.com/
2. React documentation: https://reactjs.org/docs/getting-started.html
3. Docker Compose documentation: https://docs.docker.com/compose/
4. The existing codebase for the fastAPI server and React client in our GitHub repository.

# Deliverables

1. Implement a working connection between the fastAPI server and the React client using appropriate libraries and/or packages.
2. Ensure the server can accept requests from the client and return appropriate responses.
3. Update the docker-compose configuration to run both the fastAPI server and React client seamlessly.
4. Thoroughly test the connectivity and provide a demonstration of successful communication between the client and server.
5. Document the changes made to the codebase and update the README with instructions on how to run the updated application using docker-compose.

**Comment by BinniesLite** [comment]
The client can make post/get request to the server after testing with current endpoint, so this task can be more specific. My suggestion is changing this to make request to check if the user is in the database, if true let the user log in.
